retreive_content_task:
  description: >
    Effectuez une recherche approfondie et complete sur le {topic}
    Assurez vous de trouver toute information intéressante et pertinente sur
    l année en cours est {current_year}
  expected_output: >
    Une list des 10 sites avec les informations les plus pertinente sur {topic}
  agent: web_retreiver

web_scrap_task:
  description: >
    Scrap les sites web avec les informations les plus recentes et pertinentes
  expected_output: >
    Sites scrappes avec toutes les informations les plus importante
  context: [retreive_content_task]
  agent: web_scrapper

write_web_content_task:
  description: >
    Ecrit les informations de maniere clair et pertinente dans un fichier
  expected_output: >
    Toutes le contenu en accord avec le topic chacun avec une section d information.
    Fichier markdown formate en markdown sans '```'
  context: [web_scrap_task]

  agent: web_content_writter

write_file_task:
  description: >
    Ecrit le contenu informatif et pedagogique dans un ou plusieurs fichiers
  expected_output: >
    Un ou plusieurs fichiers markdown un par notion regroupable en dossier thematique avec en prefix de nom de fichier report_2025.md
    Fichier markdown formate en markdown sans '```'
  context: [write_web_content_task]

  agent: file_writter
