fetch_the_internet:
  description: >
    Effectuez une recherche approfondie sur le {topic}
    Assurez vous de trouver toute information intéressante et pertinente sur
    l année en cours est {current_year}
  expected_output: >
    Des fichiers markdown un par notion regroupable en dossier thematique avec en prefix de nom de fichier enhanced_
    Formatted as markdown without '```'
  agent: web_retreiver

master_subject:
  description: >
    Avec le contenu a ta disposition ecris plan de formation et contenu de cours
    avec les logiciels les livrables les exercices pour chaque niveau
    les projets
  expected_output: >
    Des fichiers markdown un par notion regroupable en dossier thematique
    Formatted as markdown without '```'
  agent: subject_matter_expert

front_mastering:
  description: >
    Avec le contenu a ta disposition ecris plan de formation et contenu de cours
    avec les logiciels les livrables les exercices pour chaque niveau
    les projets
  expected_output: >
    Des fichiers markdown un par notion regroupable en dossier thematique
    Formatted as markdown without '```'
  agent: graphist_ux_designer

harmonize_content:
  description: >
    Avec le contenu a ta disposition ecris un plan de formation et contenu de cours
    avec les logiciels les livrables les exercices pour chaque niveau
    les projets en te basant sur tout les contenu ecris par les agents precedent
    Tu dois produire un contenu harmonise pour que le public cible de {topic}
    progresse efficacement
  expected_output: >
    Des fichiers markdown un par notion regroupable en dossier thematique avec en prefix de nom de fichier enhanced_
    Formatted as markdown without '```'
  agent: insturctionnal_designer

scribbling:
  description: >
    Avec le contenu a ta disposition ecris le contenu final
  expected_output: >
    Des fichiers markdown un par notion regroupable en dossier thematique avec en prefix de nom de fichier final_
    Formatted as markdown without '```'
  agent: content_writter