retreive_content_task:
  description: >
    Effectuez une recherche approfondie et complete sur le {topic} et liste les listes avec des informations interessantes
  expected_output: >
    Liste de 10 URLs au format Markdown :
      - [Nom du site 1](https://url1.com)
      - [Nom du site 2](https://url2.com) {topic}
  agent: web_retreiver

web_scrap_task:
  description: >
    Scrappe CHAQUE URL de la liste fournie dans context
    Utilise l'outil ScrapeWebsiteTool pour chaque URL avec une profondeur de 1 lien
    Utilise l'outil FileWriterTool pour ecrire un fichier dont tu choisira le nom au path suivant
    C:\Users\alexl\Documents\4_CODE\7_PYTHON\crew\ai_teachers\output
  expected_output: >
    JSON mappes des sites scrappes avec toutes les informations les plus importante, tu choisiras le format
  context: [retreive_content_task]
  agent: web_scrapper

write_web_content_task:
  description: >
    Ecrit les informations de maniere clair et pertinente dans un fichier
  expected_output: >
    Toutes le contenu en accord avec le topic chacun avec une section d information.
    Fichier markdown formate en markdown sans '```'
  context: [web_scrap_task]
  agent: web_content_writter

write_file_task:
  description: >
    Ecrit le contenu informatif et pedagogique dans un ou plusieurs fichiers
  expected_output: >
    Un ou plusieurs fichiers markdown un par notion regroupable en dossier thematique avec en prefix de nom de fichier report_2025.md
    Fichier markdown formate en markdown sans '```'
  context: [write_web_content_task]

  agent: file_writter
